apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  labels:
   app  : {{ .Release.Name }}-deployment
   owner: MikeTyupa
spec: 
   replicas: {{ .Values.replicaCount }}
   selector:
    matchLabels:
     project: {{ .Release.Name }}
   template:
    metadata:
     labels:
      project: {{ .Release.Name }}
    spec:
     containers: 
     - name : {{ .Release.Name }}-app-web
       image: {{ .Values.container.image }}
       ports:
       - containerPort: 5000